### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Omgise** [kotmatross28729/WorldTooltipsShadersFix#4]
[crash-2023-12-14_16.35.38-client.txt](https://github.com/kotmatross28729/WorldTooltipsShadersFix/files/13670735/crash-2023-12-14_16.35.38-client.txt)

**Comment by kotmatross28729** [comment]
Are there any steps to reproduce? (the crash occurs only after certain actions, or did the crash happen accidentally?)
For now, try this version and send fml-client-latest.log:
[test.zip](https://github.com/kotmatross28729/WorldTooltipsShadersFix/files/13671094/test.zip)
(open the archive, there will be a jar file inside)

**Comment by Omgise** [comment]
This crash happened by accident, and it may be difficult for me to recreate it

**Comment by Omgise** [comment]
Maybe it has been fixed and I think it is possible to close the issue temporarily and reopen it when there is a problem 🤔

**Comment by kotmatross28729** [comment]
I’m not sure, I just added a few debug prints to find out which variable is null (crash - NullPointerException), but there is not a single message in the logs that any of the variables are null (quite a strange crash). I'll leave it open for now. If it happens again, please let me know.

**Comment by Omgise** [comment]
Okay, if the crash happens again, I'll let you know soon.

**Comment by Omgise** [comment]
[crash-2023-12-25_12.27.23-client.txt](https://github.com/kotmatross28729/WorldTooltipsShadersFix/files/13763900/crash-2023-12-25_12.27.23-client.txt)
[fml-client-latest.log](https://github.com/kotmatross28729/WorldTooltipsShadersFix/files/13763902/fml-client-latest.log)

**Comment by kotmatross28729** [comment]
Yeah, now I see that in the logs it says: `mc.objectMouseOver == null`
I added a null check for some values ​​and it should work now.
Check this version so that this crash doesn't happen before I can release it:

[worldtooltips-1.2.3-83.zip](https://github.com/kotmatross28729/WorldTooltipsShadersFix/files/13765963/worldtooltips-1.2.3-83.zip)


(as usual, archive and jar file inside)

**Comment by Omgise** [comment]
Yes, I checked it and it was repaired, thank you!
