### ISSUE TITLE
[Suggestion] Make the default tooltips in the game have different colors as well

### ISSUE THREAD

**Issue by Omgise** [kotmatross28729/WorldTooltipsShadersFix#5]
![1715503509_2_wRui](https://github.com/kotmatross28729/WorldTooltipsShadersFix/assets/106000018/eeabaab0-874b-4b62-a0c0-860091c3048a)

**Comment by kotmatross28729** [comment]
The tooltip colors depend on [item rarity](https://minecraft.wiki/w/Rarity),
 1) do you suggest making different frame colors for all rarities (even for common items)? (for example, an item has a rarity of "Rare", but each droped (even the same) item can have any color, for example yellow, orange, red, etc.)
  2) or you asking if the tooltip frame changes depending on the rarity of the item?
  
   If 2 - yes, if 1 - I don’t really see the point in this, but I can make it like a configuration option or something like that

**Comment by Omgise** [comment]
2

**Comment by kotmatross28729** [comment]
As far as I understand, the question has been answered?

**Comment by Omgise** [comment]
Yes

**Comment by Omgise** [comment]
Let the tooltip framework change according to the rarity of the item, such as this mod：https://modrinth.com/mod/immersive-tooltip

**Comment by Omgise** [comment]
@kotmatross28729 I found a mod previously that seems quite similar to the Legendary Tooltips mod. It modifies the in-game tooltip boxes, allowing players to freely modify a variety of exquisite graphics according to a fixed image format. You would definitely be interested :D
https://github.com/xiaoxing2005/BetterTooltipBox

**Comment by kotmatross28729** [comment]
@Omgise , Added - https://github.com/kotmatross28729/WorldTooltipsShadersFix/releases/tag/1.2.3-85
